export const dataMahsulotlar = [
  {
    nomi: "Kompyuter",
    narxi: 100,
    tanlanganmi: false,
    yoqdimi: false,
    title: "Sizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulaySizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulay",
    image: [
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=871&q=80",
        "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=871&q=80",
        "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=871&q=80",
        "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=871&q=80",
        "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=871&q=80",
      ],
      soni: 0,
      malumot: "Krossovka adidas Erkaklar uchun KAPTIR SUPER",
      sotuvchi: "adidos",
    },
    {
      nomi: "Klaviatura",
      narxi: 200,
      tanlanganmi: false,
      yoqdimi: false,
      title: "Sizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulaySizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulay",
      image: [
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
        "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=871&q=80",
        "https://ae04.alicdn.com/kf/Sc4cc9cd36b0c45f4bd283b52aeca2a4cO.jpg_480x480.jpg",
        "https://images.unsplash.com/photo-1587829741301-dc798b83add3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1165&q=80",
        "https://divino.mt/cdn/shop/products/spiegelau-vino-grande-port-glass_800x.jpg?v=1626249188",
        "https://images.uzum.uz/ceekrool08kcldtorh10/original.jpg",
      ],
      soni: 0,
      malumot: "Krossovka adidas Erkaklar uchun KAPTIR SUPER",
      sotuvchi: "adidos",
    },
    {
      nomi: "Mishka",
      narxi: 20,
      tanlanganmi: false,
      yoqdimi: false,
      title: "Sizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulaySizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulay",
      image: [
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
      ],
      soni: 0,
      malumot: "Krossovka adidas Erkaklar uchun KAPTIR SUPER",
      sotuvchi: "adidos",
    },
    {
      nomi: "Pechenye",
      narxi: 2,
      tanlanganmi: false,
      yoqdimi: false,
      title: "Sizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulaySizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulay",
      image: [
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
      ],
      soni: 0,
    },
    {
      nomi: "Shim",
      narxi: 300,
      tanlanganmi: false,
      yoqdimi: false,
      title: "Sizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulaySizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulay",
      image: [
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
      ],
      soni: 0,
      malumot: "Krossovka adidas Erkaklar uchun KAPTIR SUPER",
      sotuvchi: "adidos",
    },
    {
      nomi: "Choy",
      narxi: 10,
      tanlanganmi: false,
      yoqdimi: false,
      title: "Sizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulaySizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulay",
      image: [
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
      ],
      soni: 0,
      malumot: "Krossovka adidas Erkaklar uchun KAPTIR SUPER",
      sotuvchi: "adidos",
    },
    {
      nomi: "Telefon",
      narxi: 40,
      tanlanganmi: false,
      yoqdimi: false,
      title: "Sizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulaySizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulay",
      image: [
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
      ],
      soni: 0,
      malumot: "Krossovka adidas Erkaklar uchun KAPTIR SUPER",
      sotuvchi: "adidos",
    },
    {
      nomi: "koylak",
      narxi: 60,
      tanlanganmi: false,
      yoqdimi: false,
      title: "Sizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulaySizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulay",
      image: [
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
      ],
      soni: 0,
      malumot: "Krossovka adidas Erkaklar uchun KAPTIR SUPER",
      sotuvchi: "adidos",
    },
    {
      nomi: "Fudbolka",
      narxi: 10,
      tanlanganmi: false,
      yoqdimi: false,
      title: "Sizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulaySizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulay",
      image: [
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
      ],
      soni: 0,
      malumot: "Krossovka adidas Erkaklar uchun KAPTIR SUPER",
      sotuvchi: "adidos",
    },
    {
      nomi: "Stakan",
      narxi: 10,
      tanlanganmi: false,
      yoqdimi: false,
      title: "Sizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulaySizga 2023 yilgi klassik sport uslubi uchun zamonaviy ayollar va erkaklar yozgi poyafzallarini taqdim etamiz.Krossovkalar uchun qulay jismoniy tarbiya, shuningdek, ish uchun， yurish va sport uchun uy poyabzali va maktab poyabzali uchun juda mos keladi. Issiq va salqin mavsumlar uchun javob beradi. Dantellar poyabzalning oyoqqa yaxshiroq joylashishini ta'minlaydi. Yuqori sifatli sun'iy charmdan tayyorlangan PVX optimal polivinilxlorid platformasida bir xil issiqlikni mukammal darajada o'tkazadi. Ushbu krossovkalar kundalik kiyishda noqulaylik tug'dirmaydi, oyoq terisi terlamaydi va poyabzalning engil vazni tufayli sizni charchatmaydi. Mamlakatga sayohat qilish,piyoda yurish va faol o'yin-kulgi uchun juda qulay",
      image: [
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
      ],
      soni: 0,
      malumot: "Krossovka adidas Erkaklar uchun KAPTIR SUPER",
    sotuvchi: "adidos",
  },
];
